### ISSUE TITLE
Better password management/hashing?

### ISSUE THREAD

**Issue by holow29** [tchapi/davis#33]
It seems to me that this project uses the same password management (Digest/md5) as Baikal. Do you think it should be changed, based on the following:

https://github.com/sabre-io/Baikal/issues/514
https://github.com/sabre-io/Baikal/pull/868

**Comment by holow29** [comment]
Someone made a good point about a newer algorithm which might be better than bcrypt as well: https://github.com/sabre-io/Baikal/pull/868#issuecomment-707073967

**Comment by tchapi** [comment]
Hi @holow29 

Yes it does use a md5 hash, and this is because Baikal and Davis still support the "legacy" Digest auth (see https://github.com/sabre-io/Baikal/issues/514#issuecomment-200452931).

I am in favor of ditching Digest altogether, but I have to take a deeper look at the consequences of that.

I will try to work on that soon.
