### ISSUE TITLE
Features Request: sending mail over SMTP

### ISSUE THREAD

**Issue by mbsouth** [tchapi/davis#36]
Great Project, many thx!
It seems, this project can become a replacement for Baikal (for my part). 
Unfortunately there is an issue: sending e-mails with php mail() function. 

A framework like phpmailer or swiftmailer to sending e-mails over an SMTP server/account would be great.

**Comment by tchapi** [comment]
Hi @mbsouth 

Check the `MAILER_URL` environment variable. **Swiftmailer** is already included so you just have to configure it with your preferred SMTP server and account :)

**Comment by mbsouth** [comment]
@tchapi 
Thank you very much.

**Comment by verahawk** [comment]
@tchapi I might be completely wrong, but shouldn't it be `MAILER_DSN`?

https://github.com/tchapi/davis/blob/47ce525946fc3bdce8bec16e1d2e789190637660/config/packages/mailer.yaml#L3

I can't find `MAILER_URL` anywhere in the code.

**Comment by tchapi** [comment]
Hi @verahawk 

It is now `MAILER_DSN` on `master` since **SwiftMailer** was replaced with **symfony/mailer** but so far, no new release has been created with this change.

So if you're using `master` (not recommended), it's `MAILER_DSN` yes. Otherwise it's still `MAILER_URL` until i create the new release (which will probably be 1.9.0)

Hope that makes sense
Best regards !

**Comment by verahawk** [comment]
Thanks for the clarification. So, I presume that this line needs to be updated on `master`:
 
https://github.com/tchapi/davis/blob/47ce525946fc3bdce8bec16e1d2e789190637660/docker/docker-compose.yml#L39

**Comment by tchapi** [comment]
You are **perfectly** right, I'm on it !

**Comment by tchapi** [comment]
Fixed in https://github.com/tchapi/davis/commit/ebdfe9fcd572e5182b43960900177fcb9ef6a8af
