### ISSUE TITLE
Notes not working

### ISSUE THREAD

**Issue by tiiiecherle** [tchapi/davis#4]
Hey,

we would like to use the notes feature. I added a calendar (with only notes instance functionality to a new user) but when adding the account to iOS or macOS the connection to the server and the account works, but it only presents calendar and contacts as options, not notes. Is there anything that has to be activated or changed to use this?

Perhaps it does not have to be added as a calendar, but as a note specified in the first place.

Thanks for looking into it and for the help in advance

Kind regards

**Comment by tchapi** [comment]
Hello @tiiiecherle 

I guess you should rather open a ticket on sabre/dav side because **davis** only provides a convenient wrapper and administration panel so I think if there's a problem on that side, it must be related to the underlying implementation of notes.

Or, maybe for some clients to work, you have to enable calendar and contacts too for notes to work ? On macOS at least, I know the client side implementation is not very consistent with the standard ...

BR

**Comment by tiiiecherle** [comment]
Thanks, done and referenced ;)

**Comment by tchapi** [comment]
I'm closing this following the answer of @evert on the related issue.
