### ISSUE TITLE
Unable to bringing up davis using docker-compose

### ISSUE THREAD

**Issue by joaofl** [tchapi/davis#84]
I followed your instructions from here in order to get the dav servers up, as from here
https://github.com/tchapi/davis#full-stack

After doing the first run migration, I can access the dashboard without any problem.

However, I get error 500 when trying to access the status root page:
![image](https://user-images.githubusercontent.com/8092452/216170684-408bac01-1a85-426f-92bc-9b771a03311e.png)

And also any address under `http://my-ip:9000/dav`

I also could not yet fully understand where to expect the webdav paths to be shared outside the docker, or what I am actually missing.

The three logs from the nginx db and davis containers look good, except for the lines reflecting the error 500.

```
192.168.80.4 -  01/Feb/2023:21:34:12 +0000 "GET /index.php" 500
```

Any idea what could the problem be?

Thanks for the support, and congrats for the initiative.

**Comment by tchapi** [comment]
Hi there 👋🏼 
Can you show me the application logs? They should be in somewhere in `./var/log` (relative to the app path) in the applicative container (davis)

**Comment by tchapi** [comment]
Yes, `sabre/dav` (the underlying dav lib) is complaining about the webdav folders. What did you set them to?

**Comment by joaofl** [comment]
I kept the defaults... I believe it was not mentioned on the README. In any case, I believe the normal user would assume those to already be mapped outside the docker?

I'll give a try asap and eventually propose some improvements on the compose, such that the bring-up requires the minimum changes.

**Comment by tchapi** [comment]
The defaults are:

```
WEBDAV_TMP_DIR='/tmp'
WEBDAV_PUBLIC_DIR='/webdav'
```

but they **must exist**, either in the container directly (but that's not really what you want for a persistent setup), or mapped to a local folder (so you can keep them between container reboots).

In any case, the rights must be correctly set so that the container user can r/w to them. If they're in the container, it's generally not a problem (the default `/tmp` works well, and you just need to create the `/webdav` folder or set it to `/tmp` too since anyway, nothing will persist). If you're mapping to a local directory, then I generally tend to create a volume named (for instance) `webdav_volume`, and use it in the container as such (in the `docker-compose.yml` file)

```
    volumes:
      - webdav_volume:/webdav
```

But then again, that requires that you set the rights correctly from _within the container_ (it's simpler) with `chmod/chown` so that the container user can access it

**Comment by joaofl** [comment]
After adding that volume it works, but to some extent..

One thing which is not working is the `.env.local` overwrite. Settings that I change there are not applied, so I need to change the on the actual .env file so they are applied.

Another thing which I am not sure is how to use the webdav. once I connect from my file browser (naltilus) to `<myip>:9000/dav/webdav` I am prompted for user/pass, which allow me to connect just fine. But once I try to create a dir or file, I gets lots of errors on the log. Am I missing something? 

In any case, shouldn't this be on the `docker-compose.yml` file by default?
```yml
@@ -55,9 +55,12 @@ services:
       - mysql
     volumes:
       - davis_www:/var/www/davis
+      - webdav:/webdav
 
 volumes:
   davis_www:
     name: davis_www
   database:
     name: database
+  webdav:
+    name: webdav

```

**Comment by tchapi** [comment]
> One thing which is not working is the `.env.local` overwrite. Settings that I change there are not applied, so I need to change the on the actual .env file so they are applied.

You should use env vars, not overwrite the `.env.local` file

> If I create a file/folder directly inside the /webdav dir

With which user? On the container or on the host?

> I try to create a dir or file, I gets lots of errors on the log

Which kind of errors?
